### ISSUE TITLE
Problem in Frontpage.html rendering due to missing custom_fields `ingv:cover`

### ISSUE THREAD

**Issue by fpistagna** [ingv-oe-dev/oedatarep-invenio-rdm#5]
If a record does not have defined the custom_field `ingv:cover`
rendering the frontpage fails.

--

`inja2.exceptions.UndefinedError: 'dict object' has no attribute 'custom_fields'`

**Comment by mtorrisi** [comment]
This issue will not be fixed because default `invenio-app-rdm` will be used.
